---
- name: "Composer: check if installed"
  stat: "path={{ composer_path }}/composer"
  register: composer_bin

- name: "Composer: download installer"
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
  when: not composer_bin.stat.exists

- name: "Composer: run installer"
  command: "php /tmp/composer-installer.php --install-dir={{ composer_path }} --filename=composer"
  when: not composer_bin.stat.exists
