---
- include_vars: "{{ ansible_os_family }}.yml"
- include: "setup-{{ ansible_os_family }}.yml"

- include: "permissions.yml"
- include: "composer.yml"
- include: "configure.yml"

- name: Ensure php-fpm is started and enabled at boot.
  service:
    name: "{{ fpm_service }}"
    state: started
    enabled: yes
    use: "{{ init_system | default(omit) }}"
