---

- name: PHP | Install Ondrej PHP PPA
  apt_repository: repo="ppa:ondrej/php"
  when: php_ver != '7.2'

- name: PHP | Install PHP and additional modules
  apt:
    name: "{{ php_packages }}"
    state: latest

- name: "Composer: check if installed"
  stat: "path=/usr/bin/composer"
  register: composer_bin

- name: "Composer: download installer"
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
  when: not composer_bin.stat.exists

- name: "Composer: run installer"
  command: "php /tmp/composer-installer.php --install-dir=/usr/bin --filename=composer"
  when: not composer_bin.stat.exists

- stat: "path={{ fpm_pool }}.bak"
  register: fpm_pool_bak

- name: Backup fpm_pool file
  shell: >
    cp {{ fpm_pool }} {{ fpm_pool }}.bak
    creates={{ fpm_pool }}.bak
  when: not fpm_pool_bak.stat.exists

- name: Configure fpm_pool
  ini_file: path={{ fpm_pool }} section=www option={{ item.name }} value={{ item.value }}
  with_items: "{{ fpm_pool_options }}"

- name: Restart php-fpm
  service:
    name: "{{ fpm_service }}"
    state: restarted
